version: "3.3"
services: 
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      labels:
        build.commit: ${BUILD_COMMIT}
        build.date: ${BUILD_DATE}
    image: ${REPO_NAME:-ndidplatform}/api:${DOCKER_TAG:-latest}

  mq:
    build:
      context: ../
      dockerfile: docker/Dockerfile-mq
      labels:
        build.commit: ${BUILD_COMMIT}
        build.date: ${BUILD_DATE}
    image: ${REPO_NAME:-ndidplatform}/mq:${DOCKER_TAG:-latest}

  telemetry-client:
    build:
      context: ../
      dockerfile: docker/Dockerfile-telemetry
      labels:
        build.commit: ${BUILD_COMMIT}
        build.date: ${BUILD_DATE}
    image: ${REPO_NAME:-ndidplatform}/telemetry-client:${DOCKER_TAG:-latest}
